export const QUESTIONS: Record<string, string[]> = {
  pdkt: [
    "Kalau kamu lagi dapet bad news, kamu tipe orang yang pengen langsung cerita atau butuh waktu sendiri dulu?",
    "Menurut kamu, hal apa dari penampilan atau vibes seseorang yang paling cepet bikin kamu ngeturn-on secara platonik?",
    "Ada gak ekspektasi dari orang luar tentang cara kamu nyari pasangan yang sebenernya bikin kamu risih?",
    "Kalau kita lagi jalan terus tiba-tiba kehujanan deras, kamu bakal milih neduh sambil ngobrol atau nerobos aja?",
    "Apa opini kamu tentang ngomongin mantan di awal-awal masa PDKT? Apakah itu wajib atau red flag?",
    "Gimana cara kamu merespons kalau tahu orang yang lagi deket sama kamu punya circle pertemanan yang toxic?",
    "Apa hal kecil yang menurut orang lain sepele, tapi kalau dilakuin ke kamu bisa bikin kamu baper seharian?",
    "Kalau disuruh mendeskripsikan tipe ideal kamu pake analogi cuaca, kamu bakal milih cuaca yang kayak gimana?",
    "Ada gak kebiasaan chat dari seseorang yang langsung bikin kamu males buat bales lagi?",
    "Apa batasan yang paling krusial buat kamu saat masih di fase pendekatan kayak sekarang?",
    "Menurut kamu, seberapa penting kecocokan selera musik atau film dalam nentuin lanjut-tidaknya sebuah hubungan?",
    "Gimana cara kamu nunjukin ketertarikan ke seseorang tanpa kelihatan terlalu agresif atau desperate?",
    "Apa momen paling absurd yang pernah kamu alamin pas lagi nyoba impresif di depan orang yang kamu taksir?",
    "Kalau kamu bisa tahu satu hal tentang masa depan finansial orang yang lagi deket sama kamu, apa yang pengen kamu tahu?",
    "Apa ketakutan terbesar kamu pas mulai ngebuka hati lagi buat orang baru?",
    "Menurut kamu, nge-date pertama itu lebih cocok di tempat yang tenang biar bisa ngobrol atau tempat seru biar gak canggung?",
    "Gimana pandangan kamu tentang konsep 'split bill' pas pertama kali jalan bareng?",
    "Apa pujian paling aneh tapi berkesan yang pernah kamu terima dari orang yang pernah deket sama kamu?",
    "Kalau kamu ngerasa feeling-nya udah gak dapet pas PDKT, kamu tipe yang bakal ghosting atau ngomong jujur?",
    "Apa hal yang paling sering bikin orang salah paham pas pertama kali kenal atau ngelihat kamu?",
    "Seberapa besar pengaruh pendapat sahabat-sahabat kamu dalam nentuin kamu bakal nerima seseorang atau gak?",
    "Apa skill atau keahlian random yang pengen banget kamu pamerin ke orang yang lagi kamu taksir?",
    "Kalau kamu dikasih kesempatan buat ngatur itinerary date seharian penuh tanpa mikirin budget, kita bakal ke mana aja?",
    "Apa satu pertanyaan yang paling kamu hindari kalau lagi ditanya sama orang yang lagi deketin kamu?",
    "Gimana cara kamu ngebedain antara orang yang beneran tulus pengen kenal sama yang cuma penasaran sesaat?",
    "Menurut kamu, butuh waktu berapa lama buat seseorang sampai bisa mutusin buat komitmen pacaran?",
    "Apa barang atau benda yang wajib ada di dalam tas kamu setiap kali kamu mau pergi ngedate?",
    "Kalau kamu nemu ketidakcocokan prinsip di awal PDKT, kamu bakal bertahan buat nyoba toleransi atau langsung mundur?",
    "Apa ekspektasi kamu yang paling realistis terhadap sosok yang bakal jadi pacar kamu nanti?",
    "Gimana cara kamu ngadepin situasi kalau ternyata gebetan kamu gak dapet restu atau gak disukain sama keluarga kamu?"
  ],
  couple: [
    "Apa momen di mana kamu merasa kontribusi kamu dalam hubungan ini kurang dihargai, walau cuma hal kecil?",
    "Gimana cara kita berdua bisa tetep berkembang ngejar mimpi masing-masing tanpa harus ngerasa mengorbankan waktu berdua?",
    "Ada gak kebiasaan buruk aku yang porsinya udah mulai ganggu kenyamanan atau produktivitas kamu akhir-akhir ini?",
    "Kalau kita dihadapkan pada pilihan finansial yang sulit, kamu lebih milih kita hemat bareng atau cari side hustle bareng?",
    "Apa hal dari cara kita berdebat atau nyelesaiin masalah yang menurut kamu masih perlu diperbaiki banget?",
    "Gimana cara kamu ngelihat pembagian peran antara kita berdua kalau nanti kita melangkah ke jenjang yang lebih serius?",
    "Pernah gak kamu ngerasa cemburu sama seseorang dari masa lalu aku tapi kamu milih buat mendam sendiri?",
    "Apa bentuk support emosional dari aku yang paling ampuh buat balikin mood kamu pas lagi drop karena kerjaan?",
    "Gimana kita bisa mastiin kalau quality time kita bener-bener berkualitas, bukan cuma sekadar duduk bareng sambil main HP?",
    "Apa ketakutan terbesar kamu yang belum pernah kamu ceritain terkait dinamika hubungan kita akhir-akhir ini?",
    "Menurut kamu, apakah kita udah cukup transparan soal masalah personal atau masih ada area yang sengaja ditutupin?",
    "Apa kompromi paling berat yang pernah kamu lakuin demi ngejaga hubungan kita tetep stabil sampai sekarang?",
    "Gimana cara terbaik buat kita untuk saling ngingetin kalau salah satu dari kita udah mulai keluar dari track goals bareng?",
    "Pernah gak tindakan atau perkataan aku secara gak sengaja bikin kamu ngerasa gak pede sama diri kamu sendiri?",
    "Apa hal baru yang pengen kita terapin dalam hubungan ini biar gak kejebak dalam rutinitas yang monoton?",
    "Gimana kita menyikapi perbedaan cara pandang kita soal hobi atau kesenangan masing-masing yang gak bisa dipaksain sama?",
    "Apa batasan baru yang menurut kamu perlu kita sepakati bareng seiring berjalannya hubungan kita yang makin dewasa?",
    "Kalau ada masalah internal di antara kita, siapa orang luar yang paling kamu percaya buat dimintain saran atau penengah?",
    "Gimana pendapat kamu tentang cara aku memperlakukan orang-orang di sekitar kamu, kayak temen atau keluarga kamu?",
    "Apa target personal kamu tahun ini yang kamu pengen aku terlibat penuh buat ngebantu kamu nyapainya?",
    "Gimana cara kamu ngatasin rasa jenuh kalau tiba-tiba fase flat atau bosan itu dateng di hubungan kita?",
    "Apa memori pahit di antara kita yang menurut kamu udah clear, tapi efek traumanya masih kadang muncul?",
    "Menurut kamu, apa hal paling berharga yang udah kita bangun bareng-bareng dan gak boleh rusak karena alasan apapun?",
    "Gimana cara kita tetep bisa punya privasi masing-masing tanpa memicu rasa curiga atau salah paham?",
    "Apa hal dari diri aku yang paling bikin kamu merasa aman dan tenang setiap kali kamu lagi ada di titik terendah?",
    "Kalau kita dapet rezeki nomplok, apa investasi atau rencana jangka panjang yang paling pertama pengen kamu diskusiin?",
    "Gimana cara kita menjaga konsistensi rasa sayang ini biar gak kemakan sama kesibukan dunia kerja masing-masing?",
    "Apa ekspektasi kamu tentang cara kita merayakan anniversary atau momen-momen penting kita ke depannya?",
    "Menurut kamu, bagian mana dari sifat aku yang paling melengkapi kekurangan terbesar yang ada di diri kamu?",
    "Gimana cara kamu ngomong ke aku kalau kamu lagi butuh ruang sendiri tanpa bikin aku ngerasa bersalah atau tersisih?"
  ],
  ldr: [
    "Gimana cara kamu ngondisiin hati pas lagi dapet bad day di tempat kerja tapi gak bisa langsung meluk aku buat tenangin diri?",
    "Apa penyesuaian jadwal paling berat yang harus kamu lakuin demi bisa sinkron sama waktu luang aku tiap harinya?",
    "Pernah gak kamu ngerasa capek banget harus terus-terusan interaksi lewat layar sampai rasanya pengen vakum komunikasi dulu?",
    "Gimana cara kita mastiin kalau obrolan harian kita gak berubah jadi sekadar absen kegiatan mekanis yang ngebosenin?",
    "Apa hal dari lingkungan sekitar kamu yang paling sering bikin kamu kangen banget sama kehadiran fisik aku di sana?",
    "Gimana cara kamu ngatasin asumsi atau overthinking yang muncul pas chat aku tiba-tiba slow respon karena kesibukan?",
    "Menurut kamu, apa tantangan terbesar yang bakal kita hadapi pas nanti kita bener-bener udah satu kota atau tinggal bareng?",
    "Apa rules atau kesepakatan virtual yang menurut kamu perlu kita perbarui biar hubungan jarak jauh ini gak makin hambar?",
    "Pernah gak kamu ngerasa minder atau insecure pas ngelihat temen kantor atau circle kamu sering dijemput pasangannya?",
    "Gimana cara kita tetep bisa ngerasain growth atau berkembang bareng meskipun kita gak bisa ngelakuin aktivitas fisik bareng?",
    "Apa bentuk perhatian kecil dari jauh yang paling efektif bikin kamu ngerasa dicintai meskipun jaraknya ratusan kilo?",
    "Gimana strategi kamu buat nolak atau ngebatasin interaksi sama orang baru di sana yang coba buat deketin kamu?",
    "Menurut kamu, seberapa besar jarak ini ngebantu kita buat melatih kemandirian emosional masing-masing?",
    "Apa hal pertama yang bakal kamu evaluasi dari hubungan kita kalau semisal jadwal ketemu kita terpaksa mundur lagi?",
    "Gimana cara kita ngebangun trust yang solid banget sampai omongan negatif orang luar soal LDR gak mempan ke kita?",
    "Apa rencana konkret yang bisa kita cicil dari sekarang buat mempercepat realisasi target endgame kita?",
    "Pernah gak kamu sengaja sembunyiin masalah berat di sana karena gak mau bikin aku ikutan kepikiran dari jauh?",
    "Gimana cara kita ngebagi porsi keuangan buat dana darurat LDR, kayak buat tiket dadakan kalau ada hal urgent?",
    "Apa satu hal dari karakter aku yang baru kamu sadari justru makin kelihatan kuat dan konsisten semenjak kita LDR?",
    "Gimana caramu ngerayain pencapaian besar kamu di sana kalau aku cuma bisa ngasih selamat lewat video call?"
  ],
  deep: [
    "Apa ketakutan eksistensial terbesar kamu tentang makna hidup yang selama ini sengaja kamu alihkan pake kesibukan?",
    "Kalau kamu disuruh milih antara hidup tenang tanpa pencapaian besar atau hidup penuh tekanan tapi legacy kamu diingat sejarah?",
    "Gimana cara kamu membedakan antara ego yang sehat untuk proteksi diri dengan egois yang merugikan orang lain?",
    "Apa trauma atau luka batin dari masa lalu yang porsinya paling besar dalam ngebentuk cara kamu merespons konflik sekarang?",
    "Menurut kamu, apakah manusia itu pada dasarnya dilahirkan baik lalu dirusak lingkungan, atau sebaliknya?",
    "Gimana cara kamu berdamai dengan kenyataan bahwa ada beberapa impian masa muda yang emang gak akan pernah terwujud?",
    "Apa penyesalan moral terbesar dalam hidupmu yang gak pernah kamu ceritain ke siapapun karena takut di-judge?",
    "Menurut kamu, kapan batas toleransi seseorang dalam memaafkan kesalahan berulang sebelum itu disebut kebodohan?",
    "Gimana pandangan kamu tentang konsep takdir? Apakah hidup kita udah diatur atau 100 persen hasil pilihan kita?",
    "Apa hal yang paling bikin kamu ngerasa terasing atau kesepian bahkan saat kamu lagi bareng orang-orang terdekat?",
    "Gimana cara kamu menjaga nilai kejujuran di tengah dunia modern yang sering kali nuntut kita buat penuh kepalsuan?",
    "Apa bagian dari kepribadian kamu yang paling sering kamu sembunyiin karena takut orang lain bakal pergi kalau tahu?",
    "Menurut kamu, apa esensi sejati dari sebuah penderitaan? Apakah itu perlu buat proses pendewasaan seseorang?",
    "Gimana cara kamu ngadepin momen kering emosional, di mana kamu gak ngerasa sedih, seneng, atau peduli sama apapun?",
    "Apa standar sukses versi kamu sendiri yang bener-bener lepas dari intervensi atau ekspektasi orang tua dan sosial?",
    "Kalau kamu bisa nanya satu hal ke Tuhan atau semesta dan langsung dapet jawaban mutlak, apa yang mau kamu tanyain?",
    "Gimana cara kamu memaafkan orang yang bahkan gak pernah ngerasa bersalah atau minta maaf atas damage yang mereka buat?",
    "Apa hal paling berani yang pernah kamu lakuin yang bener-bener ngubah arah hidup kamu sampai ke titik sekarang?",
    "Menurut kamu, apakah cinta sejati itu beneran ada atau cuma konstruksi biologis manusia buat bertahan hidup?",
    "Gimana cara kamu ngatasi krisis identitas pas kamu ngerasa semua label atau peran kamu di dunia ini mendadak ilang?",
    "Apa memori masa lalu yang paling sering muncul di pikiran kamu pas kamu lagi ngalamin burnout atau stres berat?",
    "Gimana pandangan kamu tentang kematian? Apakah itu akhir yang menenangkan atau sesuatu yang harus ditakuti?",
    "Apa hal paling egois yang pernah kamu lakuin tapi kalau waktunya diputar ulang kamu bakal tetep ngelakuin hal itu?",
    "Gimana cara kamu ngebangun kembali rasa percaya yang udah hancur total akibat pengkhianatan di masa lalu?",
    "Menurut kamu, apa hal dari perkembangan teknologi sekarang yang paling fatal dalam ngerusak bonding emosional antar manusia?",
    "Apa pujian atau kritik dari orang lain yang efeknya paling destruktif buat mental kamu dalam jangka waktu lama?",
    "Gimana cara kamu tetep waras dan punya harapan pas ngelihat realita dunia yang makin chaotic dan gak adil?",
    "Apa bentuk kompromi terbesar terhadap prinsip hidupmu yang terpaksa kamu lakuin demi bisa survive di lingkungan kerja?",
    "Kapan momen terakhir kali kamu ngerasa bener-bener terkoneksi secara spiritual atau mendalam dengan diri sendiri?",
    "Apa pesan yang pengen kamu sampaikan ke generasi setelah kamu tentang esensi terberat dari proses menjadi dewasa?",
    "Gimana cara kamu ngadepin rasa iri pas liat orang yang gak sekadar sukses, tapi dapet kemudahan hidup yang gak adil?",
    "Apa luka masa kecil yang sampai sekarang masih sering refleks bikin kamu defensif pas lagi diskusi intens?",
    "Menurut kamu, apakah kebahagiaan itu sebuah pilihan yang bisa di-force atau hasil dari kondisi eksternal yang mendukung?",
    "Gimana cara kamu memproses rasa duka atau kehilangan mendalam agar gak berubah jadi kepahitan hidup yang permanen?",
    "Apa satu prinsip hidup yang kalau kamu langgar, kamu ngerasa kamu udah gak punya harga diri lagi sebagai manusia?",
    "Gimana cara kamu menyikapi perbedaan nilai moral yang tajam antara diri kamu dengan orang tua kamu sekarang?",
    "Apa rahasia terbesar tentang caramu berpikir yang menurutmu bakal bikin orang lain kaget kalau mereka bisa baca pikiranmu?",
    "Menurut kamu, apakah uang bener-bener bisa merubah karakter asli seseorang atau cuma ngebuka topeng aslinya aja?",
    "Gimana cara kamu ngukur value diri kamu sendiri pas semua pencapaian eksternal kamu lagi drop total?",
    "Apa hal dari dunia modern ini yang menurutmu paling over-rated tapi dipuja-puja sama kebanyakan orang?",
    "Kalau kamu diberi kesempatan buat ngapus satu penyesalan terbesar dari masa lalumu, apakah kamu bakal ngambil kesempatan itu?",
    "Gimana cara kamu ngadepin situasi di mana pilihan yang bener menurut moral kamu justru nyakitin orang yang kamu sayang?",
    "Apa arti 'pulang' yang sesungguhnya buat kamu pas kondisi jiwa kamu lagi bener-bener babak belur?",
    "Siapa orang yang paling kamu harapkan validasinya dalam hidup ini, walau kamu tahu itu mungkin gak sehat?",
    "Gimana caramu mengontrol kecenderungan self-destructive atau merusak diri sendiri pas lagi ngerasa gagal total?",
    "Menurut kamu, apakah hubungan pernikahan di era sekarang itu makin rapuh karena kurangnya komitmen atau tingginya kesadaran ego?",
    "Apa hal paling absurd dari ekspektasi sosial tentang umur dan pencapaian yang paling sering bikin kamu muak?",
    "Gimana cara kamu membedakan orang yang beneran peduli sama kesehatan mental kamu dengan yang cuma jadiin itu bahan gosip?",
    "Apa mimpi terbesar kamu yang terpaksa kamu kubur karena sadar kapasitas diri atau realita ekonomi gak mendukung?",
    "Kalau hidupmu saat ini adalah sebuah buku, apa judul bab yang paling tepat buat menggambarkan fasemu sekarang?",
    "Gimana cara kamu ngadepin orang yang dengan sengaja make kelemahan atau rahasia yang pernah kamu ceritain buat nyerang kamu?",
    "Menurut kamu, apa hal paling krusial yang hilang dari pola komunikasi anak muda zaman sekarang dibanding zaman dulu?",
    "Apa bentuk self-reward paling jujur versi kamu yang gak ada hubungannya sama pamer atau konsumerisme?",
    "Gimana cara kamu merespons ketika kamu tahu kamu udah jadi toxic atau problematik buat orang di sekitar kamu?",
    "Apa ketakutan terbesar kamu tentang masa tua nanti? Apakah kesepian, penyakit, atau ketidakberdayaan finansial?",
    "Menurut kamu, seberapa penting sebuah pengakuan atau apresiasi dari publik atas apa yang udah kamu kerjain?",
    "Gimana caramu nolak permintaan bantuan dari temen deket tanpa harus ngerasa bersalah atau ngerusak pertemanan?",
    "Apa satu hal yang paling kamu syukuri dari caramu dibesarkan oleh orang tua, terlepas dari segala kekurangannya?",
    "Gimana cara kamu mendeteksi kalau motivasi kamu dalam ngejar sesuatu udah mulai bergeser ke arah yang gak sehat?",
    "Menurut kamu, apakah takdir buruk itu murni sial atau ada andil kelalaian dari keputusan masa lalu kita sendiri?",
    "Apa hal paling berat yang harus kamu relakan pergi dari hidupmu demi bisa dapet kedamaian mental kayak sekarang?",
    "Gimana cara kamu memposisikan diri pas berada di antara dua kelompok yang sama-sama kamu sayang tapi lagi konflik besar?",
    "Apa satu kalimat dari orang asing yang pernah kamu denger secara gak sengaja tapi efeknya ngerubah mindset hidupmu?",
    "Gimana cara kamu menjaga bara semangat kamu tetep nyala pas target yang kamu kejar terus-terusan nemu jalan buntu?",
    "Jika hari ini adalah kesempatan terakhirmu buat ngomong, apa kebenaran paling jujur yang pengen kamu sampaikan ke dunia?"
  ],
casual: [
    "Kalau kamu dapet kekuatan super buat bisa denger isi pikiran hewan, hewan apa yang pertama kali mau kamu ajak gibah?",
    "Apa resep atau kombinasi makanan instan paling eksperimental versi kamu yang rasanya ternyata mind-blowing?",
    "Kalau tiba-tiba dunia diserang zombie, apa barang pertama di kamar kamu sekarang yang bakal kamu jadiin senjata?",
    "Apa nama grup WhatsApp paling random atau absurd yang pernah ada di histori chat HP kamu?",
    "Lebih milih terjebak di dalam mall semalaman sendirian atau terdampar di perpustakaan kuno yang gak ada internetnya?",
    "Apa tren internet atau sound TikTok/Reels saat ini yang menurut kamu paling sukses bikin kamu cringe maksimal?",
    "Kalau kamu diundang masuk ke dalam talkshow internasional, kira-kira karena keahlian random apa kamu dipanggil?",
    "Apa barang paling murah yang pernah kamu beli tapi fungsi dan keawetannya bener-bener di luar nalar?",
    "Lebih milih dapet kupon makan gratis seumur hidup di warteg atau dapet free coffee di cafe estetik selama setahun?",
    "Apa kebohongan paling kocak yang pernah kamu buat pas jaman sekolah demi bisa bolos jam pelajaran?",
    "Kalau kamu disuruh bikin satu sekuel film yang wajib diproduksi sekarang juga, film apa yang mau kamu lanjutin?",
    "Apa isi wishlist e-commerce kamu sekarang yang paling aneh dan sebenernya gak penting-penting amat buat dibeli?",
    "Lebih milih bersin tapi gak keluar-keluar selama seharian atau cegukan setiap kali kamu mau mulai ngomong?",
    "Apa game jadul atau game masa kecil yang sampai sekarang masih sering kamu mainin diam-diam kalau lagi gabut?",
    "Kalau kamu punya kloningan diri sendiri selama 24 jam, tugas atau kesibukan mana yang bakal kamu limpahin ke dia?",
    "Apa perdebatan makanan paling gak penting yang menurut kamu harus dipertahankan sampai mati? Bubur diaduk atau tim soto?",
    "Kalau kamu terpaksa harus ganti nama panggung atau nama alias, nama keren apa yang bakal kamu pilih?",
    "Apa channel YouTube atau akun kreator paling random yang sering kamu tonton pas lagi insomnia malam-malam?",
    "Lebih milih pake baju kebalik seharian di tempat umum atau typo parah pas ngirim email formal ke atasan/dosen?",
    "Apa hal pertama yang bakal kamu lakuin kalau tiba-tiba bangun pagi dan sadar kamu berubah jadi lawan jenis?",
    "Kalau kamu disuruh bikin satu aturan lalu lintas baru khusus buat pengendara di Indonesia, aturan apa yang mau kamu buat?",
    "Apa meme atau video absurd yang porsinya paling sering kamu kirim ke temen deket buat nge-spam chat mereka?",
    "Lebih milih gak bisa tidur pake bantal seumur hidup atau harus selalu tidur pake kaos kaki basah?",
    "Apa kebiasaan refleks kamu yang paling aneh pas lagi kaget atau bener-bener panik karena hal sepele?",
    "Kalau hidup kamu dijadiin game RPG, kira-kira apa stat tertinggi dan skill pasif yang ada di karakter kamu?",
    "Kalau wifi rumah kamu mendadak mati total selama seminggu penuh, aktivitas non-gadget apa yang bakal bikin kamu survive?",
    "Apa fobia paling aneh atau tidak rasional yang kamu miliki tapi orang lain sering menganggapnya lucu?",
    "Lebih milih suara kamu berubah jadi logat kartun setiap kali lagi marah besar atau nangis sambil ketawa ngakak?",
    "Kalau kamu harus bertahan hidup di dalam minimarket 24 jam selama sebulan, lorong makanan mana yang pertama kamu amankan?",
    "Apa hal paling memalukan yang pernah kamu beli karena tergiur review algoritma FYP, padahal akhirnya gak kepake sama sekali?",
    "Lebih milih kehilangan kemampuan buat bedain rasa asin dan manis atau gak bisa ngerasain pedas seumur hidup?",
    "Jika semua barang mati di kamar kamu tiba-tiba bisa ngomong, benda mana yang paling tahu rahasia memalukanmu?",
    "Apa teori konspirasi paling absurd atau gak masuk akal yang diam-diam sempat kamu percaya porsinya?",
    "Kalau kamu mendadak jadi miliarder dalam semalam, barang receh apa yang tetep bakal kamu tawar pas belanja?",
    "Lebih milih punya gaya rambut aneh permanen yang gak bisa diganti atau selalu salah kostum tiap kali dateng ke acara formal?",
    "Apa aplikasi di HP kamu yang paling jarang dibuka tapi tetep gak mau kamu uninstall karena alasan sentimental?",
    "Kalau kamu dikasih kesempatan buat nyoba satu profesi ekstrem selama sehari tanpa risiko cedera, kamu mau nyoba jadi apa?",
    "Lebih milih dapet kiriman paket misterius setiap minggu yang isinya random atau dapet akses gratis semua layanan streaming seumur hidup?",
    "Apa kebiasaan makan kamu yang paling sering diprotes atau dianggap sekte aneh oleh circle pertemanan dekatmu?",
    "Kalau hidup kamu punya soundtrack background music otomatis kayak di film, lagu apa yang bakal muter pas kamu lagi mager?"
  ],
  darkHorse: [
    "Menurut kamu, apakah wajar kalau seseorang tetep punya rasa tertarik secara fisik ke orang lain pas udah punya pasangan?",
    "Apa batas toleransi kamu soal kebohongan finansial? Misal pasangan nyembunyiin utang atau nominal tabungan asli demi aman.",
    "Kalau kamu tahu sahabat pacar kamu suka sama kamu diam-diam, kamu bakal ngomong ke pacar kamu atau diem aja demi adem?",
    "Menurut opini kontroversial kamu, apakah selingkuh non-fisik kayak emotional cheating itu jauh lebih ngerusak dibanding physical?",
    "Apa hal paling manipulatif yang pernah refleks kamu lakuin demi menangin argumen atau dapet perhatian dari seseorang?",
    "Gimana pandangan kamu tentang konsep 'open relationship' atau poliamori? Apakah itu murni kebebasan atau pelarian dari komitmen?",
    "Apa indikator paling toxic dari diri kamu sendiri yang sadar atau gak sadar sering bikin hubungan masa lalu kamu hancur?",
    "Menurut kamu, apakah murni kesalahan satu pihak jika kasus perselingkuhan terjadi, atau ada andil kelalaian dari pasangannya?",
    "Apa pandangan kontroversial kamu tentang mantan yang tiba-tiba ngajak berteman baik lagi setelah putus secara tidak baik-baik?",
    "Seberapa jauh kamu bakal mentoleransi pasangan yang terbukti masih sering kepo atau stalking akun media sosial lamanya mantan?",
    "Menurut kamu, apakah boleh memanfaatkan rasa bersalah pasangan atas kesalahan masa lalunya demi mendapatkan keuntungan dalam argumen baru?",
    "Apa batasan tersembunyi yang kalau dilanggar oleh pasangan secara verbal, bakal langsung bikin rasa respek kamu ilang total tanpa ampun?",
    "Gimana pendapat kamu tentang orang yang sengaja bikin skenario 'tes kesetiaan' buat pasangannya lewat akun fake atau bantuan temen?",
    "Menurutmu, apakah ada situasi di mana memutuskan hubungan secara sepihak lewat chat tanpa penjelasan (ghosting) itu sepenuhnya bisa dibenarkan?"
  ]
};
