export const QUESTIONS: Record<string, string[]> = {
  pdkt: [
    "Apa asumsi pertama yang melintas di pikiranmu pas pertama kali ngelihat profil atau muka aku?",
    "Kalau cara komunikasi seseorang di awal kenalan diibaratkan game, genre apa yang paling bikin kamu betah maininnya?",
    "Apa red flag terselubung yang biasanya gak disadari orang lain, tapi langsung bikin kamu mundur teratur dari gebetan?",
    "Menurut kamu, lebih baik jujur tapi terkesan buru-buru atau nahan perasaan demi nyari waktu yang bener-bener pas?",
    "Apa topik obrolan yang menurutmu paling ampuh buat ngetes apakah seseorang beneran nyambung secara intelektual sama kamu?",
    "Gimana respon kamu kalau di tengah dinner kencan pertama, gebetan kamu ketahuan gak sopan sama staf restoran?",
    "Apa kebiasaan receh di media sosial yang bisa langsung nurunin rasa tertarikmu ke orang yang lagi deketin kamu?",
    "Kalau kita mendadak batal jalan karena urusan mendesak, cara reschedule kayak gimana yang menurutmu paling elegan?",
    "Seberapa besar ruang yang kamu kasih buat opini keluarga besar pas kamu baru mulai tahap awal pengenalan sama orang baru?",
    "Apa bentuk validasi awal yang paling kamu butuhin buat mutusin kalau proses PDKT ini layak dilanjutin ke komitmen?",
    "Menurutmu, seberapa akurat tebakan 'first impression' kamu selama ini dalam menilai karakter asli orang baru?",
    "Gimana caramu ngasih sinyal halus kalau kamu ngerasa obrolan di chat udah mulai hambar dan butuh ganti topik?",
    "Apa ketakutan tersirat yang paling sering muncul pas kamu sadar kamu udah mulai naro ekspektasi ke gebetan baru?",
    "Kalau kamu disuruh milih, mending diajak nge-date ke tempat yang fancy banget atau tempat tersembunyi yang punya cerita?",
    "Gimana caramu menyikapi perbedaan frekuensi chat antar orang yang punya kesibukan kerjaan intensif?",
    "Apa batasan privasi digital yang paling haram buat dilewatin selama status kita masih sebatas teman dekat?",
    "Menurut opini kamu, seberapa efektif konsep 'tarik ulur' dalam mempertahankan rasa penasaran pas masa PDKT?",
    "Apa pertanyaan paling klise dari gebetan yang sebenernya udah bikin kamu bosen buat ngejawabnya ulang?",
    "Gimana cara kamu membedakan antara orang yang beneran percaya diri dengan yang cuma sekadar pamer topeng ego?",
    "Kalau tiba-tiba mantan dari gebetanmu muncul lagi buat ganggu proses pendekatan, apa tindakan tegas pertama kamu?",
    "Apa elemen dari bahasa tubuh seseorang yang paling cepet ngasih tahu kamu kalau dia lagi gak nyaman pas jalan bareng?",
    "Menurutmu, apakah wajar kalau kita masih aktif di dating apps pas kita udah nemu satu orang yang potensial?",
    "Gimana caramu ngadepin situasi kalau selera humor orang yang lagi deket sama kamu ternyata garing banget?",
    "Apa prinsip dasar finansial yang wajib disepakati secara implisit bahkan sebelum status hubungan berubah jadi pacaran?",
    "Kalau kamu harus mendeskripsikan arti kenyamanan dalam fase PDKT pake satu kata benda, apa benda yang kamu pilih?",
    "Gimana respon emosional kamu kalau tahu gebetanmu ternyata masih sering cerita soal perkembangannya ke lawan jenis lain?",
    "Menurutmu, apa indikator paling valid yang nandain kalau masa pendekatan udah kelamaan dan harus segera diputusin?",
    "Apa jenis hadiah pertama yang menurutmu paling bermakna karena nunjukin kalau si pemberi bener-bener merhatiin kamu?",
    "Gimana caramu nolak ajakan kencan kedua dari orang yang setelah kencan pertama ternyata gak dapet chemistry-nya sama sekali?",
    "Apa satu hal dari caraku merespon pesanmu selama ini yang paling ngebekas atau bikin kamu mikir ulang?",
    "Menurut pandanganmu, apakah kecocokan zodiak atau love language itu hal krusial atau cuma sekadar hiburan semata?",
    "Gimana caramu tetep jadi diri sendiri tanpa harus berusaha keras kelihatan sempurna di depan orang yang kamu taksir?",
    "Apa hal paling berani yang pernah kamu lakuin demi bisa dapet kontak atau perhatian dari seseorang di masa lalu?",
    "Kalau gebetanmu ternyata punya gaya hidup yang jauh lebih konsumtif dibanding kamu, kamu bakal adaptasi atau mundur?",
    "Menurutmu, seberapa penting keterbukaan soal riwayat hubungan masa lalu pas kita baru masuk minggu pertama PDKT?",
    "Gimana caramu ngatasi rasa canggung pas tiba-tiba ada momen hening total di tengah obrolan tatap muka pertama?",
    "Apa kebiasaan burukmu sendiri pas lagi salting yang paling sering pengen kamu sembunyiin dari gebetan?",
    "Kalau kamu dikasih tahu kalau gebetanmu punya masa lalu yang kelam tapi udah berubah, apa respon pertamamu?",
    "Menurutmu, apakah nge-date di hari kerja (weekday) setelah pulang kantor itu ide yang seru atau malah bikin burnout?",
    "Apa satu pertanyaan krusial yang sebenernya pengen kamu tanyain ke aku dari kemarin tapi masih kamu tahan?"
  ],
  couple: [
    "Di bagian mana dari rutinitas harian kita yang menurutmu kita udah mulai kehilangan percikan romantisnya?",
    "Gimana cara terbaik kita buat kompromi pas gaya komunikasi kita lagi tabrakan antara logika keras vs emosi empatik?",
    "Apa ketakutan finansial jangka panjang yang paling sering kamu pikirin tapi sengaja gak kamu bahas pas kita santai?",
    "Pernah gak kamu merasa keputusan sepihak dari aku secara gak langsung ngebatesin ruang gerak karir atau hobimu?",
    "Gimana kita bisa ngejaga keseimbangan antara waktu bareng temen satu circle dengan waktu berdua tanpa ada yang tersinggung?",
    "Apa kritik paling membangun dari aku yang sebenernya sempat bikin kamu sakit hati tapi kamu sadar itu bener?",
    "Menurutmu, apa hal paling egois yang tanpa sadar masih sering kita lakuin ke satu sama lain pas lagi capek kerja?",
    "Gimana caramu menilai cara kita berdua mengelola stres di depan satu sama lain selama beberapa bulan terakhir ini?",
    "Apa ekspektasi terselubungmu soal pembagian tanggung jawab rumah tangga yang menurutmu belum kita omongin secara clear?",
    "Pernah gak kamu ngerasa aku kurang peka pas kamu lagi butuh divalidasi, bukan malah dikasih solusi logis?",
    "Gimana kita menyikapi perubahan fisik atau sifat masing-masing seiring bertambahnya usia hubungan kita?",
    "Apa bentuk trauma masa lalu dari hubungan kita yang menurutmu efeknya masih sering bikin kamu defensif pas kita argumen?",
    "Menurut pandanganmu, seberapa sehat tingkat ketergantungan emosional kita berdua saat ini? Apakah udah masuk fase co-dependent?",
    "Gimana cara kita mastiin kalau interaksi fisik kita tetep dilandasi keintiman emosional, bukan sekadar pemenuhan kebiasaan?",
    "Apa batasan baru terkait interaksi dengan lawan jenis di dunia kerja yang menurutmu perlu kita tegasin lagi sekarang?",
    "Pernah gak kamu ngerasa minder dengan pencapaian karir atau finansial aku, terus milih buat nutup diri?",
    "Gimana strategi kita buat tetep punya 'me time' yang berkualitas tanpa memicu kecurigaan atau rasa kesepian di pihak lain?",
    "Apa kebiasaan burukku yang paling sering bikin kamu tarik napas dalam-dalam demi nahan sabar sebelum merespon?",
    "Menurutmu, kapan momen di mana kita berdua bener-bener solid sebagai tim pas lagi ngadepin masalah eksternal?",
    "Gimana cara kita ngomongin masalah ranjang atau keintiman fisik secara terbuka tanpa ada pihak yang merasa dihakimi?",
    "Apa target investasi atau kepemilikan aset bareng yang menurutmu harus mulai kita cicil pembahasannya dari tahun ini?",
    "Pernah gak perkataan candaan aku di depan umum atau temen-temenmu sebenernya bikin kamu ngerasa direndahin?",
    "Gimana cara kita menjaga rasa respek tetep tinggi bahkan di momen pas kita lagi berantem hebat dan penuh emosi?",
    "Menurutmu, apa hal luar biasa dari hubungan kita yang gak akan bisa kamu temuin di hubungan orang lain?",
    "Apa satu kompromi prinsip hidup yang sampai sekarang masih bikin kamu rada ganjel demi bisa jalan bareng aku?",
    "Gimana caramu ngasih tahu aku kalau kamu lagi ngerasa jenuh sama pola hubungan kita tanpa memicu pertengkaran baru?",
    "Apa peran keluarga masing-masing yang menurutmu porsinya udah mulai terlalu masuk ke dalam ranah keputusan internal kita?",
    "Gimana kita bisa tetep saling dukung pas mimpi personal kita ternyata bertolak belakang dari segi lokasi atau waktu?",
    "Apa memori liburan atau perjalanan berdua yang paling bikin kamu sadar kalau aku adalah orang yang tepat buat masa depanmu?",
    "Gimana cara kita mengevaluasi perkembangan hubungan ini secara berkala biar gak sekadar jalan di tempat tanpa arah?",
    "Menurutmu, seberapa transparan kita harus berbagi password device atau akun personal demi ngebangun trust?",
    "Apa hal kecil dari caraku menyambut kamu pulang atau setelah seharian gak ketemu yang paling bisa ngilangin capekmu?",
    "Gimana kita ngadepin situasi kalau salah satu dari kita mendadak harus nanggung beban finansial keluarga besarnya?",
    "Apa ketakutan terbesarmu kalau nanti kita udah masuk ke fase pernikahan dan rutinitasnya jauh lebih monoton?",
    "Pernah gak kamu ngerasa aku terlalu mendominasi dalam setiap pengambilan keputusan penting di hubungan ini?",
    "Gimana caramu nunjukin rasa terima kasih atas hal-hal kecil yang udah aku lakuin tanpa kelihatan formalitas belaka?",
    "Apa bagian dari masa lalu kita yang pengen banget kamu hapus dari ingatan karena terlalu menyakitkan buat diingat?",
    "Gimana kita memposisikan diri pas ada perbedaan pandangan politik atau prinsip sosial yang mendadak tajam di antara kita?",
    "Menurutmu, apa hal paling krusial yang harus kita persiapkan sebelum memutuskan buat melangkah ke jenjang legal?",
    "Apa pesan paling jujur yang pengen kamu titip ke aku buat dipegang pas hubungan kita nanti diterpa badai besar?"
  ],
  ldr: [
    "Gimana caramu mengusir rasa sepi mendadak pas lagi di tempat umum dan ngelihat banyak pasangan lain jalan bareng?",
    "Apa kendala teknis atau perbedaan waktu yang paling sering bikin kamu frustrasi pas lagi pengen deep talk?",
    "Pernah gak muncul pikiran buat nyerah sama keadaan jarak ini pas komunikasi kita lagi delay karena sinyal atau kesibukan?",
    "Gimana cara kita mendeteksi kalau salah satu dari kita udah mulai nyari kenyamanan emosional dari orang lain di sekitarnya?",
    "Apa barang peninggalan fisik dari aku yang paling sering kamu pegang pas rasa kangennya udah di ubun-ubun?",
    "Gimana caramu ngondisiin pikiran biar gak gampang kemakan asumsi buruk pas denger cerita temenmu yang gagal LDR?",
    "Menurutmu, seberapa efektif sesi date virtual (nonton bareng/makan bareng lewat layar) dalam ngejaga kedekatan kita?",
    "Apa hal dari caraku ngomong di telepon yang langsung bisa ketahuan kalau aku lagi nyembunyiin kesedihan atau stres?",
    "Gimana cara kita ngatur budget khusus buat ketemu biar gak ngeganggu pos tabungan masa depan kita?",
    "Pernah gak kamu ngerasa bersalah karena gak bisa ada di samping aku pas aku lagi sakit atau ngalamin musibah?",
    "Gimana caramu ngejelasin ke circle pertemananmu yang sering mempertanyakan masa depan hubungan jarak jauh kita ini?",
    "Apa kebiasaan baru di tempat tinggalmu sekarang yang paling pengen kamu tunjukin langsung pas nanti aku dateng ke sana?",
    "Menurutmu, apakah jarak ini malah bikin rasa sayang kita makin matang atau justru pelan-pelan kikis karena jarang ketemu?",
    "Gimana kita nyikapin momen canggung yang kadang muncul di beberapa menit pertama pas kita akhirnya ketemu fisik setelah lama pisah?",
    "Apa satu aturan komunikasi wajib yang gak boleh dilanggar sama sekali selama kita terpisah jarak ratusan kilometer?",
    "Pernah gak kamu ngerasa iri sama kemudahan komunikasi pasangan normal yang bisa langsung ketemu cuma buat makan malam?",
    "Gimana strategi kamu buat tetep fokus kerja di sana tanpa terus-terusan keganggu pikiran pengen ngecek HP?",
    "Menurutmu, apa tanda paling jelas kalau kualitas hubungan LDR kita lagi ngalamin penurunan drastis?",
    "Apa hal pertama yang mau kamu lakuin bareng aku pas nanti masa LDR kita bener-bener udah berakhir selamanya?",
    "Gimana cara kita ngerayain hari jadian atau momen penting dengan cara kreatif meskipun terpisah jarak geografis?",
    "Pernah gak kamu ngerasa duniaku di sini berjalan terlalu cepat sampai kamu takut ketinggalan atau gak relevan lagi?",
    "Gimana caramu meredam rasa cemburu pas tahu aku lagi ada acara bareng temen-temen kantor yang ada lawan jenisnya?",
    "Apa satu kelebihan dari sistem LDR yang menurutmu malah bikin kita berdua jadi individu yang jauh lebih mandiri?",
    "Gimana kita mutusin kota mana yang bakal kita jadiin tempat tinggal permanen pas target endgame kita terlaksana?",
    "Apa ekspektasimu soal intensitas komunikasi pas salah satu dari kita lagi dapet tugas dinas lapangan yang minim sinyal?"
  ],
  deep: [
    "Apa definisi kesuksesan batin yang paling murni buat kamu setelah semua validasi duniawi kamu singkirkan?",
    "Kalau kamu harus berterima kasih pada satu kegagalan terbesar di masa lalu, kegagalan mana yang paling membentuk jiwamu?",
    "Gimana caramu membedakan antara rasa bersalah yang membangun dengan self-blame yang destruktif buat mentalmu?",
    "Apa aspek dari caramu dibesarkan yang paling keras usahamu buat diputus rantainya agar gak nurun ke anak-cucu?",
    "Menurutmu, apakah kedamaian pikiran bisa dicapai tanpa harus mengorbankan ambisi besar dalam dunia karir?",
    "Gimana caramu memproses kenyataan kalau orang yang paling kamu percaya ternyata bisa berubah jadi orang asing dalam semalam?",
    "Apa standar moral personal yang paling berat buat kamu pertahankan di tengah lingkungan yang serba menghalalkan segala cara?",
    "Menurut pandangan eksistensialmu, apa kontribusi terkecil yang wajib manusia berikan ke dunia sebelum mereka tiada?",
    "Gimana caramu berdamai dengan sisi gelap atau kelemahan karaktermu yang paling parah tanpa harus membenci diri sendiri?",
    "Apa jenis kesepian yang paling menyiksa buat kamu? Apakah sepi di tengah keramaian atau sepi karena gak dipahami?",
    "Gimana cara kamu mendeteksi kalau jiwamu udah mulai lelah (burnout emosional) sebelum itu bermanifestasi jadi sakit fisik?",
    "Menurutmu, apakah pengampunan atau memaafkan itu sebuah proses instan yang diputusin atau perjalanan seumur hidup?",
    "Apa hal dari struktur sosial modern ini yang menurutmu paling sukses merenggut kebahagiaan otentik manusia?",
    "Gimana caramu menjaga harapan tetep hidup pas semua indikator logis di sekitarmu nunjukin hasil yang gagal?",
    "Apa rahasia kesedihan terdalammu yang gak pernah kamu bagi karena kamu tahu orang lain cuma bakal kasihan tanpa paham?",
    "Menurutmu, apakah kebebasan mutlak itu berkah yang membebaskan atau justru kutukan yang bikin manusia tersesat?",
    "Gimana caramu menilai arti sebuah ketulusan di era di mana semua interaksi sosial dihitung berdasarkan asas manfaat?",
    "Apa penyesalan terbesar terkait caramu memperlakukan seseorang di masa lalu yang sampai sekarang masih membekas?",
    "Menurutmu, seberapa besar andil penderitaan dalam mengikis kesombongan ego manusia buat jadi lebih bijaksana?",
    "Gimana caramu bangkit dari momen krisis finansial atau karir yang sempat bikin harga dirimu hancur lebur?",
    "Apa pandanganmu tentang konsep jodoh? Apakah itu takdir yang terkunci atau hasil perjuangan dua orang yang keras kepala?",
    "Gimana caramu mengidentifikasi kalau motivasi hidupmu udah mulai disetir oleh rasa takutan akan kemiskinan atau penolakan?",
    "Apa warisan non-materi paling berharga yang pengen kamu tinggalin buat orang-orang yang kamu sayangi nanti?",
    "Menurutmu, apakah manusia modern sekarang kehilangan kemampuan buat fokus dan refleksi mendalam karena distraksi digital?",
    "Gimana caramu menyembuhkan luka penolakan emosional dari masa lalu agar gak bikin kamu sinis sama ketulusan baru?",
    "Apa arti 'menjadi dewasa' yang paling menyakitkan yang terpaksa harus kamu telan pas masuk usia kepala dua?",
    "Gimana caramu membedakan antara intuisi batin yang bener dengan suara kecemasan (anxiety) yang menipu?",
    "Apa bentuk kompromi spiritual atau prinsip terdalam yang pernah terpaksa kamu langgar demi tuntutan survive?",
    "Menurutmu, apakah kebahagiaan itu tujuan akhir atau sekadar efek samping dari hidup yang punya makna dan fungsi?",
    "Gimana caramu ngadepin perasaan iri pas ngelihat orang yang usahanya minimal tapi dapet privilege eksternal melimpah?",
    "Apa memori masa kecil yang paling sering bikin kamu pengen balik ke masa lalu cuma buat meluk dirimu sendiri?",
    "Gimana caramu menyikapi perbedaan nilai moral yang tajam antara idealisme pribadimu dengan realita di dunia kerja?",
    "Apa topeng kepribadian yang paling sering kamu pake pas lagi terpaksa harus bersosialisasi di lingkungan toxic?",
    "Menurutmu, apakah uang bener-bener bisa beli kebahagiaan, atau cuma bisa beli alat buat ngusir penderitaan fisik?",
    "Gimana caramu mengukur value diri pas kamu lagi gak produktif dan semua rencana besarmu lagi ketunda?",
    "Apa konsep modern yang paling dinilai berlebihan (overrated) oleh orang banyak tapi menurutmu justru bikin boncos emosi?",
    "Kalau kamu diberi kesempatan buat ngapus satu keputusan salah dari masa lalumu, apakah kamu bakal ngambil atau biarin aja?",
    "Gimana caramu ngadepin situasi di mana pilihan yang bener menurut moral justru bakal ngerusak hubungan baik keluarga?",
    "Apa arti 'pulang' yang paling hakiki buat jiwamu pas kondisi mentalmu lagi bener-bener hancur berantakan?",
    "Siapa orang yang omongannya paling punya power buat ngejatuhin mentalmu dalam sekejap, dan gimana caramu proteksi diri?",
    "Gimana caramu ngerem kecenderungan sabotase diri sendiri (self-sabotage) pas segala sesuatunya sebenernya lagi berjalan lancar?",
    "Menurutmu, apakah ikatan pernikahan di generasi sekarang makin rentan karena kurangnya daya tahan atau terlalu tingginya ekspektasi?",
    "Apa tuntutan sosial berdasarkan umur yang paling bikin kamu muak dan pengen kamu dobrak aturannya?",
    "Gimana caramu membedakan orang yang beneran empati sama masalahmu dengan yang cuma penasaran buat jadiin bahan obrolan?",
    "Apa mimpi idealis terbesar kamu yang terpaksa kamu kubur karena realita ekonomi keluarga gak memungkinkan?",
    "Kalau fase hidupmu sekarang dijadiin judul film, konflik utama apa yang lagi berusaha diselesaikan oleh karakter utamanya?",
    "Gimana caramu merespon pas orang terdekatmu make kelemahan yang pernah kamu ceritain sebagai senjata pas lagi berantem?",
    "Menurutmu, apa skill emosional paling krusial yang hilang dari anak muda zaman sekarang akibat terlalu sering interaksi virtual?",
    "Apa bentuk apresiasi terbaik buat dirimu sendiri yang bener-bener bikin tenang tanpa perlu divalidasi media sosial?",
    "Gimana caramu ngakuin kesalahan dengan kesatria pas kamu sadar kalau tindakanmu udah merugikan orang sekitar?",
    "Apa ketakutan terbesar kamu tentang masa tua nanti? Apakah kesepian emosional, penyakit fisik, atau beban finansial?",
    "Menurutmu, seberapa penting pengakuan publik atas karya atau pencapaianmu dalam menentukan tingkat kepuasan hidupmu?",
    "Gimana caramu nolak permintaan pinjaman uang atau bantuan dari teman dekat tanpa ngerasa bersalah atau merusak relasi?",
    "Apa satu didikan keras dari orang tua yang dulu kamu benci tapi sekarang baru kamu sadari manfaat besarnya?",
    "Gimana caramu ngecek kalau ambisi besarmu dalam mengejar karir udah mulai berubah jadi obsesi yang gak sehat?",
    "Menurutmu, apakah nasib buruk yang bertubi-tubi itu murni faktor eksternal atau akumulasi dari pilihan sadar kita sendiri?",
    "Apa hal terberat yang terpaksa kamu ikhlaskan pergi demi kenyamanan dan kesehatan mentalmu saat ini?",
    "Gimana caramu bersikap pas kejebak di antara dua kubu pertemanan yang lagi konflik besar tanpa kelihatan bermuka dua?",
    "Apa satu kalimat dari orang asing atau buku random yang secara instan merubah total caramu memandang dunia?",
    "Gimana caramu menjaga konsistensi semangat pas semua target kerjaanmu mentok di jalan buntu berbulan-bulan?",
    "Jika hari ini adalah batas akhir komunikasimu dengan dunia, kebenaran fundamental apa yang wajib kamu suarakan?",
    "Apa batas toleransimu dalam memberikan kesempatan kedua bagi orang yang udah merusak kepercayaanmu secara sadar?",
    "Gimana caramu mengatasi kekosongan emosional pas kamu berhasil nyapai target besar tapi ngerasa biasa aja setelahnya?",
    "Menurutmu, apakah manusia bisa bener-bener tulus mencintai orang lain sebelum dia selesai dengan konflik internal dirinya sendiri?",
    "Apa aspek dari kematian yang paling sering bikin kamu merenung soal cara memanfaatkan sisa waktu hidupmu sekarang?",
    "Gimana caramu melepaskan dendam lama yang energinya tanpa sadar masih sering nahan perkembangan dirimu?"
  ],
  casual: [
    "Kalau semua barang elektronik di rumahmu mendadak punya kepribadian, benda mana yang bakal paling sering ngajak berantem?",
    "Apa eksperimen menu makanan paling nyeleneh versi kamu yang pas dicoba ternyata rasanya enak di luar dugaan?",
    "Kalau besok pagi terjadi zombie apocalypse, dua barang apa di sekitarmu sekarang yang bakal kamu jadiin senjata andalan?",
    "Apa nama grup chat di HP-mu yang isinya paling absurd dan gak jelas tujuan pembuatannya?",
    "Mending terjebak di dalam museum angker sendirian semalaman atau di bandara asing tanpa uang dan internet selama dua hari?",
    "Apa tren atau jokes internet saat ini yang menurutmu paling cringe dan gak masuk akal kenapa bisa viral?",
    "Kalau kamu mendadak viral di kancah internasional, kira-kira karena aksi random atau skill aneh apa yang kamu lakuin?",
    "Apa barang murah di bawah lima puluh ribu yang pernah kamu beli tapi kualitasnya awet sampai bertahun-tahun?",
    "Lebih milih dapet pasokan mie instan gratis seumur hidup atau kopi susu kekinian gratis setiap hari selama dua tahun?",
    "Apa alasan paling gak masuk akal yang pernah kamu pake buat ijin bolos sekolah atau kuliah zaman dulu?",
    "Kalau kamu punya wewenang buat ngapus satu genre film dari dunia ini, genre apa yang bakal kamu lenyapin?",
    "Apa isi keranjang belanjaan e-commerce kamu yang paling random dan sebenernya gak butuh-butuh amat buat check out?",
    "Mending nahan bersin yang gak keluar-keluar selama dua jam atau cegukan keras tiap kali kamu selesai ngomong tiga kata?",
    "Apa game konsol jadul atau game web masa kecil yang sampai sekarang masih suka kamu mainin pas lagi gabut parah?",
    "Kalau kamu punya kembaran kloningan selama 12 jam, tugas membosankan apa yang pertama kali bakal kamu serahin ke dia?",
    "Apa perdebatan sekte makanan yang menurutmu paling krusial buat dipertahankan? Bubur diaduk atau makan pizza pake garpu?",
    "Kalau kamu terpaksa harus ganti nama panggung yang estetik tapi kocak, nama apa yang bakal kamu gunain?",
    "Apa channel YouTube atau topik video paling random yang sering kamu tonton pas lagi susah tidur jam dua pagi?",
    "Mending salah kirim chat gibah ke orang yang lagi digibahin atau typo parah pas ngirim email lamaran kerja?",
    "Apa hal pertama yang bakal kamu cek di cermin kalau tiba-tiba bangun tidur dan sadar kamu berubah jadi lawan jenis?",
    "Kalau kamu bisa bikin satu undang-undang lalu lintas baru khusus netizen Indonesia, aturan kocak apa yang mau kamu bikin?",
    "Apa stiker atau meme yang porsinya paling sering kamu pake buat nge-spam chat temen deketmu pas lagi males ngetik?",
    "Mending gak boleh pake bantal sama sekali pas tidur seumur hidup atau harus selalu tidur pake jaket tebal berlapis?",
    "Apa reaksi refleks paling aneh dari tubuhmu pas lagi kaget karena hal sepele kayak cicak jatuh?",
    "Kalau hidupmu dirancang jadi game RPG, kira-kira skill pasif terkuat apa yang dimiliki oleh karakter kamu?",
    "Kalau internet rumah mati total seminggu, aktivitas manual apa yang bakal kamu lakuin biar gak mati gaya?",
    "Apa ketakutan atau fobia paling absurd yang kamu punya tapi sering jadi bahan ceng-cengan temenmu?",
    "Mending suara kamu berubah jadi suara karakter kartun pas lagi panik atau nangis tapi ekspresi mukanya kayak ketawa?",
    "Kalau kudu bertahan hidup di dalam supermarket selama seminggu, lorong atau bagian mana yang bakal kamu kuasai duluan?",
    "Apa barang paling gak berguna yang pernah kamu beli cuma gara-gara kemakan racun FYP TikTok atau Reels?",
    "Mending kehilangan kemampuan ngerasain makanan manis atau gak bisa ngerasain sensasi gurih seumur hidup?",
    "Jika semua perabot di kamarmu bisa ngomong, benda mana yang paling sering ngelihat momen memalukanmu pas sendirian?",
    "Apa teori konspirasi paling aneh yang diam-diam sempat kamu percayai kebenarannya pas zaman sekolah dulu?",
    "Kalau kamu mendadak dapet warisan triliunan, barang murah apa yang tetep bakal kamu tawar pas belanja di pasar?",
    "Mending rambutmu potongannya aneh permanen atau selalu salah kostum tiap kali dateng ke acara kondangan?",
    "Apa aplikasi di HP-mu yang paling jarang dibuka tapi haram buat di-uninstall karena alasan memori masa lalu?",
    "Kalau dikasih kesempatan nyoba profesi ekstrem tanpa risiko cedera selama sehari, kamu mau nyoba jadi apa?",
    "Mending dapet kiriman paket misterius tiap minggu yang isinya random atau gratis langganan bioskop seumur hidup?",
    "Apa kebiasaan makan kamu yang paling sering diprotes atau dianggap aliran sesat oleh circle pertemanan dekatmu?",
    "Kalau hidupmu punya background music otomatis kayak di film, lagu apa yang bakal muter pas kamu lagi mager parah?",
    "Apa tontonan masa kecil yang menurutmu paling membekas tapi pas ditonton sekarang ternyata ceritanya agak absurd?",
    "Kalau kamu bisa beli satu hewan eksotis buat dipelihara tanpa perlu mikirin regulasi dan biaya, kamu mau pelihara apa?",
    "Lebih milih gak bisa dengerin musik sama sekali selama sebulan atau gak bisa nonton video apa pun selama dua minggu?",
    "Apa barang di mejamu sekarang yang paling mencerminkan kondisi isi pikiranmu saat ini?",
    "Kalau kamu disuruh bikin satu festival unik tahunan di kotamu, festival apa yang pengen kamu selenggarakan?"
  ],
  darkHorse: [
    "Menurutmu, seberapa wajar kalau seseorang tetep punya ketertarikan emosional ke orang lain pas statusnya udah tunangan?",
    "Apa batas toleransi kamu soal kebohongan masa lalu? Misal pasangan nyembunyiin fakta kalau dia pernah nikah siri demi aman.",
    "Kalau kamu tahu mantan pacarmu deketin sahabatmu sendiri buat balas dendam, kamu bakal turun tangan atau biarin aja?",
    "Menurut opini kontroversialmu, apakah micropaying atau micro-cheating di medsos (like foto seksi/DM tipis) itu udah sah disebut selingkuh?",
    "Apa trik psikologis paling manipulatif yang pernah kamu gunain secara sadar demi ngontrol keputusan orang lain?",
    "Gimana pandangan sinismu tentang konsep 'soulmate'? Apakah itu cuma alat jualan industri romansa biar orang gak kesepian?",
    "Apa sisi toxic dari dirimu yang paling susah kamu kendaliin pas lagi ngerasa terancam atau cemburu buta?",
    "Menurutmu, apakah pihak ketiga sepenuhnya bersalah dalam kasus perselingkuhan, atau pembuka pintu rumahnya yang lebih berdosa?",
    "Apa opini kontroversialmu tentang tetap menjaga hubungan baik dengan mantan yang jelas-jelas udah ngerusak mentalmu?",
    "Seberapa jauh kamu mentoleransi pasangan yang masih nyimpen foto atau barang pemberian mantan dengan alasan fungsional?",
    "Menurutmu, boleh gak memanfaatkan kelemahan psikologis pasangan pas berantem demi mempercepat durasi konflik selesai?",
    "Apa kalimat atau hinaan verbal dari pasangan yang kalau sekali aja terucap, bakal langsung bikin rasa cintamu mati saat itu juga?",
    "Gimana pendapatmu tentang orang yang sengaja masang aplikasi spy atau pelacak di HP pasangannya tanpa ijin demi trust?",
    "Menurutmu, apakah ada skenario di mana balas dendam ke mantan yang toxic itu sepenuhnya bisa dibenarkan secara moral?",
    "Apa kebohongan terbesar yang pernah kamu pertahankan dalam sebuah hubungan demi menjaga status quo tetep aman?",
    "Menurut pandangan tajammu, seberapa banyak orang di sekitarmu yang sebenernya bertahan bareng pasangan cuma karena takut status jomblo?",
    "Gimana responmu kalau tahu pasanganmu diam-diam punya akun alter yang isinya bertolak belakang dari persona aslinya?",
    "Apakah menurutmu wajar jika seseorang merasa senang pas ngelihat orang yang pernah menyakitinya ngalamin kegagalan hidup?",
    "Apa batasan paling ekstrem yang bersedia kamu lewati demi ngelindungin reputasi pribadimu dari kehancuran?",
    "Menurutmu, apakah kejujuran mutlak dalam hubungan itu sebenernya utopia yang justru bakal ngerusak keharmonisan?"
  ]
};
