export const QUESTION = [
  // ==========================================
  // PDKT (Pendekatan / Dating Phase)
  // ==========================================
  "Apa kesan pertama kamu waktu pertama kali lihat aku?",
  "Apa hal yang paling penting buat kamu dalam sebuah hubungan?",
  "Lebih suka ngobrol lewat chat, telepon, atau ketemu langsung?",
  "Apa love language kamu yang paling dominan?",
  "Apa red flag terbesar menurut kamu dalam diri seseorang?",
  "Kapan terakhir kali kamu patah hati dan apa yang kamu pelajari?",
  "Apa arti 'hubungan yang sehat' menurut pandangan kamu?",
  "Gimana cara kamu mengekspresikan rasa sayang ke orang lain?",
  "Apa hal yang paling cepat bikin kamu ngerasa ilfeel?",
  "Kamu lebih suka tipe pasangan yang dominan atau yang setara?",
  "Apa hobi atau aktivitas yang lagi sering kamu lakuin sekarang?",
  "Gimana weekend ideal versi kamu?",
  "Apa film atau buku yang paling mempengaruhi cara pandang hidupmu?",
  "Lebih milih liburan ke pantai yang tenang atau gunung yang dingin?",
  "Apa makanan yang gak akan pernah kamu tolak dalam kondisi apapun?",
  "Punya kebiasaan unik atau aneh yang jarang orang tahu?",
  "Apa lagu yang paling sering kamu dengerin minggu ini?",
  "Lebih suka nongkrong di cafe estetik atau warung kopi biasa?",
  "Apa pencapaian terbesar dalam hidupmu sejauh ini?",
  "Apa ketakutan terbesar kamu yang pengen kamu kalahin?",
  "Gimana cara kamu healing kalau lagi stres berat?",
  "Apa mimpi masa kecilmu yang masih pengen diwujudin?",
  "Siapa sosok yang paling menginspirasi hidup kamu?",
  "Kalau punya uang tanpa batas, apa hal pertama yang mau kamu beli?",
  "Apa prinsip hidup yang gak akan pernah kamu langgar?",
  "Gimana hubungan kamu dengan keluarga besar sekarang?",
  "Apa memori masa kecil yang paling bikin kamu bahagia?",
  "Kamu anak ke berapa dan gimana itu membentuk karaktermu?",
  "Apa nasihat terbaik dari orang tua yang selalu kamu inget?",
  "Gimana pandangan kamu soal batasan privasi dalam keluarga?",
  "Apa jenis candaan yang paling gampang bikin kamu ketawa?",
  "Lebih suka dapet kejutan kecil atau direncanain bareng-bareng?",
  "Pernah gak terjebak dalam situasi canggung pas lagi ngedate?",
  "Apa hal paling konyol yang pernah kamu lakuin demi gengsi?",
  "Kalau hidup kamu dijadiin film, apa genre yang paling cocok?",

  // ==========================================
  // COUPLE (Dating / In a Relationship)
  // ==========================================
  "Kapan momen tepatnya kamu ngerasa kalau kamu sayang sama aku?",
  "Apa kebiasaan kecil aku yang paling sering bikin kamu senyum?",
  "Ada gak sifat aku yang awalnya aneh tapi sekarang malah kamu suka?",
  "Apa hal yang paling kamu kangenin dari aku kalau kita gak ketemu?",
  "Gimana cara aku menenangkan kamu pas kamu lagi marah atau sedih?",
  "Apa panggilan sayang dari aku yang paling kamu suka?",
  "Momen ngedate mana yang paling berkesan selama kita jalan bareng?",
  "Apa hal baru yang kamu pelajari tentang diri kamu sejak sama aku?",
  "Gimana cara kita berdua bisa jadi partner yang lebih kompak lagi?",
  "Apa ketakutan terbesar kamu tentang masa depan hubungan kita?",
  "Kalau kita lagi berantem, apa hal yang paling kamu butuhin dari aku?",
  "Menurut kamu, kita berdua paling sering berantem karena masalah apa?",
  "Apa cara terbaik buat kita berdua untuk nyelesaiin miskomunikasi?",
  "Ada gak hal dari masa lalu yang masih sering ngeganjel di hati kamu?",
  "Pernah gak aku gak sengaja ngebongkar insecurity terbesar kamu?",
  "Gimana cara kita bisa tetep romantis di tengah kesibukan masing-masing?",
  "Apa ekspektasi kamu yang belum terpenuhi dalam hubungan ini?",
  "Gimana pandangan kamu soal keuangan kalau kita nanti makin serius?",
  "Apa batasan (boundaries) yang gak boleh kita langgar satu sama lain?",
  "Gimana cara kita ngebagi waktu antara pacaran, kerjaan, dan temen?",
  "Apa target atau goals yang pengen kita capai bareng tahun ini?",
  "Gimana pendapat kamu tentang circles pertemanan aku?",
  "Apa aktivitas baru yang belum pernah kita coba tapi pengen dicoba bareng?",
  "Kalau aku tiba-tiba harus pindah tugas, kamu bakal gimana?",
  "Gimana cara kita ngejaga trust satu sama lain tetep kuat?",
  "Apa arti kesetiaan menurut kamu dalam hubungan kita sekarang?",
  "Hal apa yang menurut kamu bisa ngerusak hubungan kita secara instan?",
  "Gimana cara kamu ngelihat aku 5 tahun dari sekarang?",
  "Apa pendapat kamu tentang konsep pernikahan ideal?",
  "Hal apa dari aku yang pengen banget kamu ubah kalau bisa?",

  // ==========================================
  // LDR (Long Distance Relationship)
  // ==========================================
  "Apa hal paling berat yang kamu rasain minggu ini selama kita jauh?",
  "Gimana cara kamu ngatasin rasa sepi pas malam hari tanpa aku?",
  "Apa rutinitas komunikasi kita yang paling kamu tunggu-tunggu?",
  "Pernah gak ngerasa insecure pas aku lagi gak bisa dihubungin?",
  "Apa hal pertama yang mau kamu lakuin pas kita ketemu nanti?",
  "Gimana cara kamu ngejaga bumbu romantis tetep ada lewat layar HP?",
  "Ada gak momen di mana kamu hampir ngerasa menyerah sama jarak ini?",
  "Apa lagu yang paling sering ngingetin kamu tentang aku pas lagi LDR?",
  "Gimana cara kamu ngebedain antara kangen biasa sama kangen yang toxic?",
  "Apa barang peninggalan aku yang sering kamu pegang pas lagi kangen?",
  "Gimana cara kita ngebangun transparansi biar gak gampang curiga?",
  "Menurut kamu, apa miskomunikasi terbesar yang pernah kita alamin karena jarak?",
  "Apa rules baru yang perlu kita buat biar LDR ini terasa lebih ringan?",
  "Gimana cara kamu nanggepin pertanyaan orang lain soal hubungan LDR kita?",
  "Pernah gak kamu ngerasa iri liat orang lain bisa ngedate fisik tiap weekend?",
  "Kapan target realistis kita buat bener-bener menyudahi jarak ini (endgame)?",
  "Kota mana yang bakal kita pilih buat tinggal bareng nanti?",
  "Apa pengorbanan terbesar yang udah kamu lakuin demi bertahan di LDR ini?",
  "Gimana rencana tabungan kita buat biaya transport ketemu selanjutnya?",
  "Apa hal yang bikin kamu yakin kalau perjuangan LDR ini bakal worth it?",

  // ==========================================
  // MARRIED (Marriage Life)
  // ==========================================
  "Apa perubahan terbesar yang kamu rasain setelah kita satu atap?",
  "Gimana evaluasi kamu soal pembagian tugas rumah tangga kita sekarang?",
  "Apa hal dari kebiasaan tidur atau bangun tidurku yang paling unik?",
  "Gimana cara kita tetep bisa punya 'me time' masing-masing tanpa ngerasa jauh?",
  "Apa momen paling membahagiakan sejak kita resmi jadi suami istri?",
  "Gimana sistem pengelolaan keuangan kita sekarang, perlu ada yang diubah?",
  "Apa pandangan kamu tentang investasi jangka panjang untuk keluarga kita?",
  "Gimana cara kita ngatur budget buat liburan tanpa ngeganggu pos utama?",
  "Apa ketakutan terbesar kamu terkait stabilitas finansial rumah tangga kita?",
  "Gimana cara kita diskusiin pengeluaran besar sebelum mutusin beli?",
  "Gimana cara kita ngejaga kehidupan seksual kita tetep hangat dan memuaskan?",
  "Apa fantasi atau variasi baru yang pengen kita coba bareng-bareng?",
  "Gimana cara kita nunjukin rasa sayang di depan anak / keluarga besar?",
  "Apa arti keintiman emosional bagi kamu setelah beberapa tahun nikah?",
  "Pernah gak kamu ngerasa jenuh dengan rutinitas rumah tangga kita?",
  "Gimana pola asuh (parenting style) yang mau kita terapin ke anak?",
  "Apa prinsip utama yang harus kita ajarin ke anak sejak dini?",
  "Gimana cara kita ngebagi waktu antara urusan anak dan waktu berdua (date night)?",
  "Apa hal yang paling bikin kamu khawatir tentang masa depan anak-anak?",
  "Gimana cara kita kompak hadapin perbedaan pendapat soal urusan anak?",
  "Gimana cara kita menyikapi masukan atau campur tangan dari mertua/orang tua?",
  "Apa batasan privasi rumah tangga kita yang gak boleh diketahui orang luar?",
  "Gimana cara kita ngebantu keluarga besar tanpa bebanin finansial kita?",
  "Momen kunjungan keluarga mana yang paling bikin kamu ngerasa nyaman?",
  "Apa tradisi keluarga baru yang pengen kita bangun bareng tiap tahunnya?",
  "Apa goals besar rumah tangga kita yang pengen dicapai dalam 10 tahun ke depan?",
  "Gimana cara kita saling support buat pencapaian karir masing-masing?",
  "Kalau nanti kita pensiun, kamu pengen kita menghabiskan masa tua di mana?",
  "Apa penyesalan yang paling kamu hindari dalam membangun keluarga ini?",
  "Kalau kamu bisa balik ke hari pernikahan kita, apa pesan buat diri kita saat itu?",

  // ==========================================
  // DEEP & REFLECTIVE (Bonus Mix)
  // ==========================================
  "Apa arti kebahagiaan sejati menurut kamu di fase hidup yang sekarang?",
  "Kalau kamu bisa mengubah satu hal dari masa lalumu, apa yang mau diubah?",
  "Gimana cara kamu berdamai dengan kegagalan yang pernah kamu alamin?",
  "Apa definisi sukses yang paling realistis buat kamu saat ini?",
  "Siapa orang yang paling ingin kamu mintai maaf tapi belum kesampaian?",
  "Apa hal yang paling sering bikin kamu overthinking sebelum tidur?",
  "Gimana pandangan kamu tentang kehidupan setelah kematian?",
  "Apa warisan atau legacy yang pengen kamu tinggalkan buat dunia ini?",
  "Gimana cara kamu menjaga kesehatan mental di tengah tekanan hidup?",
  "Apa momen dalam hidupmu yang paling menguji iman atau prinsipmu?",
  "Kalau kamu tahu besok dunia kiamat, apa 3 hal yang bakal kamu lakuin hari ini?",
  "Apa penyesalan terbesar yang masih sering membayangi kamu?",
  "Gimana cara kamu memaafkan orang yang udah ngecewain kamu terlalu dalam?",
  "Apa hal yang paling kamu syukuri dari hidup kamu sampai detik ini?",
  "Menurut kamu, apa bagian dari diri kamu yang paling sulit dipahami orang lain?",

  // ==========================================
  // CASUAL (Santai, Ringan, Ice Breaking)
  // ==========================================
  "Kalau kamu jadi karakter anime atau kartun, kamu mau jadi siapa?",
  "Apa isi tab browser kamu yang paling aneh atau gak penting sekarang?",
  "Lebih milih gak bisa pake medsos sebulan atau gak makan mie instan tiga bulan?",
  "Apa tren fashion atau tren internet yang menurut kamu paling cringe?",
  "Kalau tiba-tiba dapet uang kaget 10 juta malam ini, mau dipake buat apa?",
  "Apa meme atau video lucu yang terakhir kali bikin kamu ketawa ngakak?",
  "Lebih milih jadi manusia gak kasat mata atau bisa terbang tapi cuma setinggi satu meter?",
  "Apa toping pizza paling ilegal menurut kamu? Nanas, durian, atau apa?",
  "Kalau disuruh milih, mendingan kuah bakso kemanisan atau sambal gak ada pedasnya sama sekali?",
  "Apa kebiasaan aneh kamu pas lagi sendirian di kamar mandi?",
  "Pernah gak salah kirim chat salah masuk grup? Ceritain dong!",
  "Lebih suka dengerin podcast horor, konspirasi, atau komedi?",
  "Kalau bisa tukar nasib sama satu selebritis selama 24 jam, mau tukar sama siapa?",
  "Apa nama kontak aku di HP kamu waktu pertama kali kamu simpan?",
  "Kalau kita terdampar di pulau terpencil, kira-kira siapa yang bakal survive duluan?",
  "Apa barang paling gak berguna tapi tetep kamu beli karena lapar mata?",
  "Lebih milih kuah soto dipisah atau dicampur? Ini krusial ya!",
  "Apa game yang paling sering bikin kamu emosi tapi tetep kamu mainin?",
  "Kalau kamu disuruh bikin satu aturan hukum baru yang wajib dipatuhi semua orang, apa aturannya?",
  "Apa kebohongan paling random yang pernah kamu ucapin ke temen kamu pas lagi malas keluar rumah?",
  "Lebih milih ketahuan kentut di lift penuh orang atau sendawa keras pas lagi hening?",
  "Apa akun sosmed yang paling sering kamu stalk belakangan ini?",
  "Kalau hidup ini ada tombol 'undo', momen memalukan mana yang mau kamu hapus?",
  "Apa kombinasi makanan paling aneh yang menurut kamu rasanya justru enak banget?",
  "Lebih suka tidur pake lampu mati total, remang-remang, atau terang benderang?",

  // ==========================================
  // DARK HORSE / UNPOPULAR OPINIONS (Tambahan)
  // ==========================================
  "Apa opini kontroversial kamu tentang komitmen yang kira-kira bakal bikin orang lain nge-judge kamu?",
  "Kalau kamu tahu pasangan kamu selingkuh tapi cuma sekali dan dia jujur, kamu bakal maafin atau langsung cut?",
  "Menurut kamu, apakah berbohong demi kebaikan (white lies) itu beneran ada atau cuma justifikasi aja?",
  "Apa hal yang paling egois yang pernah kamu lakuin dalam hubungan masa lalu kamu?",
  "Lebih milih punya pasangan yang pinter banget tapi cuek, atau yang biasa aja tapi perhatiannya berlebihan?",
  "Menurut kamu, boleh gak kita tetep nyimpen barang dari mantan kalau barang itu beneran berguna?",
  "Apa indikator utama yang bikin kamu ngerasa sebuah hubungan udah bener-bener mati dan gak bisa diselamatin?"
];
